server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~ ^/(login|wallet_transactions|wallet_users|wallet_categories|user_wallets|currencies|client_log|language|default_wallet|user|wallet|category|transaction|wallet_generate_link|wallet_verify_link|bot_user_wallets|bot_user_language|bot_default_wallet|bot_transaction|docs|openapi\.json)(/.*)?$ {
        proxy_pass http://backend:8000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
