version: "3.5"

services:

  backend:
    build: ./backend
    command: sh run_server.sh
    ports:
      - 8000:8000
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TOKEN: ${TOKEN}
      SECRET_KEY: ${SECRET_KEY}
      BOT_SECRET: ${BOT_SECRET}
    networks:
      - postgres
    depends_on:
      - db
    restart: always

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: cashflow
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: always

  frontend:
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 80:80
      - 443:443
    restart: always

  bot:
    build: ./bot
    environment:
      TOKEN: ${TOKEN}
      WEBAPP_URL: ${WEBAPP_URL}
      API_URL: ${API_URL}
      BOT_SECRET: ${BOT_SECRET}
      WEBAPP_TG_URL: ${WEBAPP_TG_URL}
    restart: always

networks:
  postgres:
    driver: bridge
